---
title: "penguins_anova"
author: "Michael Allen"
date: "November 6, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


1. load packages and read in data

```{r include = FALSE}
library(tidyverse)
library(car)
library(onewaytests)

penguins <- read_csv("penguins.csv")
```


Is there a significant difference in mean flipper length for female penguins by species (Chinstrap, Gentoo, Adelie)?


2. explore the data

new functions: with + table for easy counting for multiple factors

update species name using case_when

```{r}

counts <- with(penguins, table(species, sex))
counts

penguins2 <- penguins %>%
  mutate(common_name = 
           case_when(
             species == "Chinstrap penguin (Pygoscelis antarctica)" ~ "Chinstrap",
             species == "Gentoo penguin (Pygoscelis papua)" ~ "Gentoo",
             species == "Adelie Penguin (Pygoscelis adeliae)" ~ "Adelie"
           )
  ) %>%
  select(-species) %>%
  filter(sex =="FEMALE")
```

```{r}

hists <- ggplot(penguins2, aes(x = flipper_length)) +
  geom_histogram(aes(fill = common_name)) +
  facet_wrap(~ common_name)

hists

qqplot <- ggplot(penguins2, aes(sample = flipper_length)) +
  geom_qq() +
  facet_wrap(~ common_name)
qqplot
```

```{r}
# levies tests for equal variance (when groups > 2), otherwise use the f test

# H0: variances are equal
# H1: variances are unequal

penguin_levene <- leveneTest(flipper_length ~ common_name, data = penguins2) # as a function of flipper length grouped by common_anme 
penguin_levene

# variances are just slightly equal


penguin_vars <- penguins2 %>%
  group_by(common_name) %>%
  summarize(
    variance = var(flipper_length)
  )
```

